/*
 * Terrarium guest: TypeScript — checked, stripped, and run inside the sandbox.
 *
 * QuickJS-ng with the real TypeScript compiler embedded as precompiled QuickJS
 * bytecode. Each eval: fetch the host-generated SDK `.d.ts` (reserved "$dts"
 * cap), type-check the submitted source against it (strict; skipped by a
 * leading `// @ts-nocheck`), erase the types whitespace-preserving
 * (ts-blank-space, so runtime error lines match the TS source exactly), then
 * evaluate the resulting JavaScript exactly like the plain QuickJS guest.
 *
 * Two contexts, one lifetime rule:
 *  - the "compiler" JSRuntime/JSContext (TypeScript + libs + driver) is created
 *    once per wasm instance and persists across evals — lib parsing and Program
 *    state amortize in shared mode;
 *  - the "user" JSRuntime/JSContext is fresh per eval, identical to the plain
 *    QuickJS guest.
 *
 * Same host ABI as every other guest:
 *   - exports `memory` and `guest_alloc(len) -> ptr` (host->guest writes)
 *   - exports `eval(ptr, len) -> packed` where the argument is a msgpack string
 *     (the TS source) and the result is `(retPtr << 32) | retLen` (msgpack)
 *   - imports host.host_call(name_ptr, name_len, args_ptr, args_len) -> packed
 *
 * A check failure comes back as the standard sentinel
 * { "$error": {message: "TS2345: ...", type: "TS2345", line} }.
 *
 * Built with the WASI SDK in reactor mode; see build.sh.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "quickjs.h"

/* Precompiled QuickJS bytecode payloads (generated by build.sh via native qjsc
 * from the same quickjs-ng tree — bytecode is version-locked). */
extern const uint8_t qjsc_typescript[];
extern const uint32_t qjsc_typescript_size;
extern const uint8_t qjsc_libs[];
extern const uint32_t qjsc_libs_size;
extern const uint8_t qjsc_tsblank[];
extern const uint32_t qjsc_tsblank_size;
extern const uint8_t qjsc_driver[];
extern const uint32_t qjsc_driver_size;

/* The one host import. */
__attribute__((import_module("host"), import_name("host_call")))
extern int64_t host_call(int32_t name_ptr, int32_t name_len,
                         int32_t args_ptr, int32_t args_len);

/* ------------------------------------------------------------------ */
/* memory contract                                                    */
/* ------------------------------------------------------------------ */

__attribute__((export_name("guest_alloc")))
void *guest_alloc(int32_t len) {
    return malloc(len < 1 ? 1 : (size_t)len);
}

static int64_t pack(void *ptr, size_t len) {
    return ((int64_t)(uint32_t)(uintptr_t)ptr << 32) | (int64_t)(uint32_t)len;
}

/* A growable byte buffer for msgpack output. */
typedef struct {
    uint8_t *data;
    size_t len, cap;
} Buf;

static void buf_put(Buf *b, const void *p, size_t n) {
    if (b->len + n > b->cap) {
        size_t cap = b->cap ? b->cap * 2 : 64;
        while (cap < b->len + n) cap *= 2;
        b->data = realloc(b->data, cap);
        b->cap = cap;
    }
    memcpy(b->data + b->len, p, n);
    b->len += n;
}
static void buf_u8(Buf *b, uint8_t v) { buf_put(b, &v, 1); }

/* ------------------------------------------------------------------ */
/* msgpack encode: JSValue -> bytes                                   */
/* ------------------------------------------------------------------ */

static void be64(uint8_t out[8], uint64_t v) {
    for (int i = 7; i >= 0; i--) { out[i] = (uint8_t)(v & 0xff); v >>= 8; }
}

static void enc_int(Buf *b, int64_t i) {
    if (i >= 0 && i <= 127) { buf_u8(b, (uint8_t)i); return; }
    if (i >= -32 && i < 0) { buf_u8(b, (uint8_t)(int8_t)i); return; }
    uint8_t tmp[8]; be64(tmp, (uint64_t)i);
    buf_u8(b, 0xd3); buf_put(b, tmp, 8);
}
static void enc_str(Buf *b, const char *s, size_t n) {
    if (n < 32) buf_u8(b, 0xa0 | (uint8_t)n);
    else { buf_u8(b, 0xdb); uint8_t t[4]; t[0]=n>>24;t[1]=n>>16;t[2]=n>>8;t[3]=n; buf_put(b, t, 4); }
    buf_put(b, s, n);
}
static void enc_arr_hdr(Buf *b, uint32_t n) {
    if (n < 16) buf_u8(b, 0x90 | (uint8_t)n);
    else { buf_u8(b, 0xdc); uint8_t t[2]; t[0]=n>>8; t[1]=n; buf_put(b, t, 2); }
}
static void enc_map_hdr(Buf *b, uint32_t n) {
    if (n < 16) buf_u8(b, 0x80 | (uint8_t)n);
    else { buf_u8(b, 0xde); uint8_t t[2]; t[0]=n>>8; t[1]=n; buf_put(b, t, 2); }
}

static void js_to_mp(JSContext *ctx, JSValueConst v, Buf *b) {
    if (JS_IsNull(v) || JS_IsUndefined(v)) { buf_u8(b, 0xc0); return; }
    if (JS_IsBool(v)) { buf_u8(b, JS_ToBool(ctx, v) ? 0xc3 : 0xc2); return; }
    if (JS_IsFunction(ctx, v)) { buf_u8(b, 0xc0); return; }
    if (JS_IsNumber(v)) {
        double d;
        JS_ToFloat64(ctx, &d, v);
        if (isfinite(d) && d == floor(d) && fabs(d) < 9007199254740992.0)
            enc_int(b, (int64_t)d);
        else { buf_u8(b, 0xcb); uint8_t t[8]; uint64_t bits; memcpy(&bits,&d,8); be64(t,bits); buf_put(b,t,8); }
        return;
    }
    if (JS_IsString(v)) {
        size_t n; const char *s = JS_ToCStringLen(ctx, &n, v);
        enc_str(b, s ? s : "", s ? n : 0);
        if (s) JS_FreeCString(ctx, s);
        return;
    }
    if (JS_IsArray(v)) {
        int64_t n = 0;
        JSValue lv = JS_GetPropertyStr(ctx, v, "length");
        JS_ToInt64(ctx, &n, lv); JS_FreeValue(ctx, lv);
        enc_arr_hdr(b, (uint32_t)n);
        for (int64_t i = 0; i < n; i++) {
            JSValue el = JS_GetPropertyUint32(ctx, v, (uint32_t)i);
            js_to_mp(ctx, el, b); JS_FreeValue(ctx, el);
        }
        return;
    }
    if (JS_IsObject(v)) {
        JSPropertyEnum *tab = NULL; uint32_t plen = 0;
        if (JS_GetOwnPropertyNames(ctx, &tab, &plen, v,
                                   JS_GPN_STRING_MASK | JS_GPN_ENUM_ONLY) < 0) {
            buf_u8(b, 0x80); return;
        }
        enc_map_hdr(b, plen);
        for (uint32_t i = 0; i < plen; i++) {
            const char *key = JS_AtomToCString(ctx, tab[i].atom);
            enc_str(b, key ? key : "", key ? strlen(key) : 0);
            if (key) JS_FreeCString(ctx, key);
            JSValue pv = JS_GetProperty(ctx, v, tab[i].atom);
            js_to_mp(ctx, pv, b); JS_FreeValue(ctx, pv);
        }
        JS_FreePropertyEnum(ctx, tab, plen);
        return;
    }
    buf_u8(b, 0xc0);
}

/* ------------------------------------------------------------------ */
/* msgpack decode: bytes -> JSValue                                   */
/* ------------------------------------------------------------------ */

typedef struct { const uint8_t *p; size_t off, len; } Rd;

static uint64_t rd_be(Rd *r, int n) {
    uint64_t v = 0;
    for (int i = 0; i < n; i++) v = (v << 8) | r->p[r->off++];
    return v;
}

static JSValue mp_to_js(JSContext *ctx, Rd *r) {
    if (r->off >= r->len) return JS_NULL;
    uint8_t m = r->p[r->off++];
    if (m <= 0x7f) return JS_NewInt64(ctx, m);
    if (m >= 0xe0) return JS_NewInt64(ctx, (int8_t)m);
    if ((m & 0xe0) == 0xa0) { /* fixstr */
        size_t n = m & 0x1f; JSValue s = JS_NewStringLen(ctx, (const char *)r->p + r->off, n);
        r->off += n; return s;
    }
    if ((m & 0xf0) == 0x90) { /* fixarray */
        uint32_t n = m & 0x0f; JSValue a = JS_NewArray(ctx);
        for (uint32_t i = 0; i < n; i++) JS_SetPropertyUint32(ctx, a, i, mp_to_js(ctx, r));
        return a;
    }
    if ((m & 0xf0) == 0x80) { /* fixmap */
        uint32_t n = m & 0x0f; JSValue o = JS_NewObject(ctx);
        for (uint32_t i = 0; i < n; i++) {
            JSValue k = mp_to_js(ctx, r);
            const char *ks = JS_ToCString(ctx, k);
            JSValue val = mp_to_js(ctx, r);
            JS_SetPropertyStr(ctx, o, ks ? ks : "", val);
            if (ks) JS_FreeCString(ctx, ks);
            JS_FreeValue(ctx, k);
        }
        return o;
    }
    switch (m) {
        case 0xc0: return JS_NULL;
        case 0xc2: return JS_NewBool(ctx, 0);
        case 0xc3: return JS_NewBool(ctx, 1);
        case 0xcc: return JS_NewInt64(ctx, rd_be(r, 1));
        case 0xcd: return JS_NewInt64(ctx, rd_be(r, 2));
        case 0xce: return JS_NewInt64(ctx, rd_be(r, 4));
        case 0xcf: return JS_NewInt64(ctx, (int64_t)rd_be(r, 8));
        case 0xd0: return JS_NewInt64(ctx, (int8_t)rd_be(r, 1));
        case 0xd1: return JS_NewInt64(ctx, (int16_t)rd_be(r, 2));
        case 0xd2: return JS_NewInt64(ctx, (int32_t)rd_be(r, 4));
        case 0xd3: return JS_NewInt64(ctx, (int64_t)rd_be(r, 8));
        case 0xca: { uint32_t bits = rd_be(r, 4); float f; memcpy(&f, &bits, 4); return JS_NewFloat64(ctx, f); }
        case 0xcb: { uint64_t bits = rd_be(r, 8); double d; memcpy(&d, &bits, 8); return JS_NewFloat64(ctx, d); }
        case 0xd9: { size_t n = rd_be(r, 1); JSValue s = JS_NewStringLen(ctx, (const char*)r->p+r->off, n); r->off += n; return s; }
        case 0xda: { size_t n = rd_be(r, 2); JSValue s = JS_NewStringLen(ctx, (const char*)r->p+r->off, n); r->off += n; return s; }
        case 0xdb: { size_t n = rd_be(r, 4); JSValue s = JS_NewStringLen(ctx, (const char*)r->p+r->off, n); r->off += n; return s; }
        case 0xdc: { uint32_t n = rd_be(r, 2); JSValue a = JS_NewArray(ctx); for (uint32_t i=0;i<n;i++) JS_SetPropertyUint32(ctx,a,i,mp_to_js(ctx,r)); return a; }
        case 0xde: { uint32_t n = rd_be(r, 2); JSValue o = JS_NewObject(ctx);
            for (uint32_t i=0;i<n;i++){ JSValue k=mp_to_js(ctx,r); const char*ks=JS_ToCString(ctx,k); JSValue v=mp_to_js(ctx,r); JS_SetPropertyStr(ctx,o,ks?ks:"",v); if(ks)JS_FreeCString(ctx,ks); JS_FreeValue(ctx,k);} return o; }
        default: return JS_NULL;
    }
}

/* ------------------------------------------------------------------ */
/* the host capability bridge                                          */
/* ------------------------------------------------------------------ */

/* __host(name, ...args) -> result, calling the host capability. */
static JSValue js_host(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv) {
    if (argc < 1) return JS_ThrowTypeError(ctx, "__host requires a capability name");

    size_t name_len; const char *name = JS_ToCStringLen(ctx, &name_len, argv[0]);
    if (!name) return JS_EXCEPTION;

    /* Encode the rest of the args as a msgpack array. */
    Buf ab = {0};
    enc_arr_hdr(&ab, (uint32_t)(argc - 1));
    for (int i = 1; i < argc; i++) js_to_mp(ctx, argv[i], &ab);

    int64_t packed = host_call((int32_t)(intptr_t)name, (int32_t)name_len,
                               (int32_t)(intptr_t)ab.data, (int32_t)ab.len);
    JS_FreeCString(ctx, name);
    free(ab.data);

    uint32_t rptr = (uint32_t)(packed >> 32);
    uint32_t rlen = (uint32_t)(packed & 0xffffffff);
    Rd r = { (const uint8_t *)(uintptr_t)rptr, 0, rlen };
    JSValue result = mp_to_js(ctx, &r);
    free((void *)(uintptr_t)rptr);
    return result;
}

/* Recursive facade + console, identical to the plain QuickJS guest: the
 * registered top-level names (reserved "$names" cap) become globals; there is
 * no synthetic root. */
static const char PRELUDE[] =
    "function __ns(p){"
    "  return new Proxy(function(){}, {"
    "    get(_t, name){ return typeof name === 'string' ? __ns(p ? p+'.'+name : name) : undefined; },"
    "    apply(_t, _th, args){ return __host(p, ...args); }"
    "  });"
    "}"
    "for (var __n = __host('$names'), __i = 0; __i < __n.length; __i++) { globalThis[__n[__i]] = __ns(__n[__i]); }"
    "globalThis.console = (function(){"
    "  var fmt = function(x){ return (typeof x === 'object' && x !== null) ? JSON.stringify(x) : String(x); };"
    "  var emit = function(){ __host('$out', Array.prototype.slice.call(arguments).map(fmt).join(' ')); };"
    "  return { log: emit, error: emit, warn: emit, info: emit, debug: emit };"
    "})();";

/* ------------------------------------------------------------------ */
/* result / error marshaling                                           */
/* ------------------------------------------------------------------ */

static int64_t ret_value(JSContext *ctx, JSValueConst v) {
    Buf b = {0};
    js_to_mp(ctx, v, &b);
    void *out = guest_alloc((int32_t)b.len);
    memcpy(out, b.data, b.len);
    free(b.data);
    return pack(out, b.len);
}

/* Encode the structured sentinel { "$error": {message, type?, line?} }. */
static int64_t ret_error_full(const char *msg, const char *type, int has_line, int64_t line) {
    Buf b = {0};
    enc_map_hdr(&b, 1);
    enc_str(&b, "$error", 6);
    enc_map_hdr(&b, 1 + (type ? 1u : 0u) + (has_line ? 1u : 0u));
    enc_str(&b, "message", 7);
    enc_str(&b, msg, strlen(msg));
    if (type) { enc_str(&b, "type", 4); enc_str(&b, type, strlen(type)); }
    if (has_line) { enc_str(&b, "line", 4); enc_int(&b, line); }
    void *out = guest_alloc((int32_t)b.len);
    memcpy(out, b.data, b.len);
    free(b.data);
    return pack(out, b.len);
}

static int64_t ret_error(const char *msg) {
    return ret_error_full(msg, NULL, 0, 0);
}

/* A thrown JS exception in the user context: name/message/stack, with the
 * source line parsed from the stack ("...<eval>:LINE..."). Because types were
 * erased whitespace-preserving, that line matches the TS source exactly. */
static int64_t ret_error_exc(JSContext *ctx, JSValueConst exc) {
    JSValue jname = JS_GetPropertyStr(ctx, exc, "name");
    JSValue jmsg = JS_GetPropertyStr(ctx, exc, "message");
    JSValue jstack = JS_GetPropertyStr(ctx, exc, "stack");
    const char *name = JS_IsString(jname) ? JS_ToCString(ctx, jname) : NULL;
    const char *msg = JS_IsString(jmsg) ? JS_ToCString(ctx, jmsg) : NULL;
    const char *stack = JS_IsString(jstack) ? JS_ToCString(ctx, jstack) : NULL;

    const char *fallback = (msg && *msg) ? NULL : JS_ToCString(ctx, exc);

    int has_line = 0;
    int64_t line = 0;
    if (stack) {
        const char *p = strstr(stack, "<eval>:");
        if (p) {
            p += 7;
            while (*p >= '0' && *p <= '9') { line = line * 10 + (*p - '0'); p++; has_line = 1; }
        }
    }

    int64_t out = ret_error_full(
        (msg && *msg) ? msg : (fallback ? fallback : "uncaught JS exception"),
        (name && *name) ? name : NULL,
        has_line, line);

    if (name) JS_FreeCString(ctx, name);
    if (msg) JS_FreeCString(ctx, msg);
    if (stack) JS_FreeCString(ctx, stack);
    if (fallback) JS_FreeCString(ctx, fallback);
    JS_FreeValue(ctx, jname);
    JS_FreeValue(ctx, jmsg);
    JS_FreeValue(ctx, jstack);
    return out;
}

/* ------------------------------------------------------------------ */
/* the persistent compiler context                                     */
/* ------------------------------------------------------------------ */

static JSRuntime *g_crt = NULL;
static JSContext *g_cctx = NULL;

static int eval_bytecode(JSContext *ctx, const uint8_t *buf, uint32_t len) {
    JSValue obj = JS_ReadObject(ctx, buf, len, JS_READ_OBJ_BYTECODE);
    if (JS_IsException(obj)) return 1;
    JSValue res = JS_EvalFunction(ctx, obj);
    if (JS_IsException(res)) return 1;
    JS_FreeValue(ctx, res);
    return 0;
}

/* Bring up TypeScript + libs + ts-blank-space + the driver, once per instance.
 * The compiler runtime persists across evals: in shared mode the lib parse and
 * Program caches amortize; isolated mode pays this once per (fresh) instance. */
static int ensure_compiler(void) {
    if (g_cctx) return 0;
    g_crt = JS_NewRuntime();
    if (!g_crt) return 1;
    /* The checker recurses deeply; give it a generous JS-level stack budget
     * (the wasm linker stack is sized to cover it — see build.sh). */
    JS_SetMaxStackSize(g_crt, 4 * 1024 * 1024);
    g_cctx = JS_NewContext(g_crt);
    if (!g_cctx) return 1;

    /* typescript.js is a CommonJS bundle: give it module/exports + a stub
     * process before evaluating its bytecode. */
    static const char CPRELUDE[] =
        "globalThis.module = { exports: {} };"
        "globalThis.exports = globalThis.module.exports;"
        "globalThis.process = { env: {}, argv: [], versions: {}, cwd: function(){ return '/'; } };";
    JSValue pre = JS_Eval(g_cctx, CPRELUDE, sizeof(CPRELUDE) - 1, "<cprelude>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(pre)) return 1;
    JS_FreeValue(g_cctx, pre);

    if (eval_bytecode(g_cctx, qjsc_typescript, qjsc_typescript_size)) return 1;

    static const char EXPORT_TS[] = "globalThis.ts = globalThis.module.exports;";
    JSValue ex = JS_Eval(g_cctx, EXPORT_TS, sizeof(EXPORT_TS) - 1, "<cprelude>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(ex)) return 1;
    JS_FreeValue(g_cctx, ex);

    if (eval_bytecode(g_cctx, qjsc_libs, qjsc_libs_size)) return 1;
    if (eval_bytecode(g_cctx, qjsc_tsblank, qjsc_tsblank_size)) return 1;
    if (eval_bytecode(g_cctx, qjsc_driver, qjsc_driver_size)) return 1;
    return 0;
}

/* ------------------------------------------------------------------ */
/* Wizer pre-initialization                                            */
/* ------------------------------------------------------------------ */

/* Wizer (build.sh, final step) calls this once, offline: it brings up the
 * compiler context — reads the ~2 MB TypeScript bytecode, evaluates it into a
 * live compiler object graph, parses the lib .d.ts chain + ts-blank-space + the
 * driver — then snapshots the resulting linear memory and globals into the
 * module's data segments. At runtime `g_cctx` is therefore already non-null, so
 * `ensure_compiler()` short-circuits on its first line: the ~1 s bootstrap is
 * paid at build time, once, and every instance (shared or a fresh isolated one)
 * starts with the compiler already warm.
 *
 * The snapshot is self-contained: `ensure_compiler()` makes no host calls (the
 * SDK .d.ts is fetched per-eval, not here), so Wizer needs no working `host`
 * import — a trapping stub suffices, and none of it fires. If bring-up fails we
 * abort rather than bake a half-initialized heap. */
__attribute__((export_name("wizer.initialize")))
void wizer_initialize(void) {
    if (ensure_compiler()) abort();

    /* Bring up the compiler object graph is not enough on its own: the ~500 ms
     * a first eval pays is `ts.createProgram` *parsing and binding the ~88 lib
     * .d.ts files*, and that happens on the first check in any fresh compiler
     * context. So run one throwaway check here too. The driver caches parsed +
     * bound lib SourceFiles (`libCache`) for the context's life; those are
     * SDK-independent, so baking them means every eval — including each fresh
     * isolated instance — reuses the warm libs instead of re-parsing them.
     * (The per-SDK Program cache can't carry over — the real SDK .d.ts is only
     * known per-eval — but the lib parse/bind is the dominant cost.) */
    static const char WARM[] =
        "__terrariumCompile('const __warm: number = 1; __warm;', '');";
    JSValue r = JS_Eval(g_cctx, WARM, sizeof(WARM) - 1, "<warmup>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(r)) abort();
    JS_FreeValue(g_cctx, r);
}

/* Fetch the SDK .d.ts from the host (reserved "$dts" cap) as a JSValue string
 * in the compiler context. */
static JSValue fetch_dts(JSContext *ctx) {
    static const char NAME[] = "$dts";
    Buf ab = {0};
    enc_arr_hdr(&ab, 0);
    int64_t packed = host_call((int32_t)(intptr_t)NAME, 4,
                               (int32_t)(intptr_t)ab.data, (int32_t)ab.len);
    free(ab.data);
    uint32_t rptr = (uint32_t)(packed >> 32);
    uint32_t rlen = (uint32_t)(packed & 0xffffffff);
    Rd r = { (const uint8_t *)(uintptr_t)rptr, 0, rlen };
    JSValue dts = mp_to_js(ctx, &r);
    free((void *)(uintptr_t)rptr);
    return dts;
}

/* ------------------------------------------------------------------ */
/* check entrypoint (optional export — type-check only, nothing runs)  */
/* ------------------------------------------------------------------ */

/* `check(ptr, len)`: the argument is a msgpack string (TS source). Returns a
 * msgpack ARRAY of every error diagnostic ({message, type, line?}); an empty
 * array means the source is well-typed against the current SDK. No user
 * context is created and no guest code executes. Ignores @ts-nocheck — an
 * explicit check asks for the diagnostics. */
__attribute__((export_name("check")))
int64_t check(int32_t ptr, int32_t len) {
    if (ensure_compiler()) {
        return ret_error("failed to start the TypeScript compiler");
    }

    Rd r = { (const uint8_t *)(uintptr_t)(uint32_t)ptr, 0, (size_t)(uint32_t)len };
    JSValue srcv = mp_to_js(g_cctx, &r);
    if (!JS_IsString(srcv)) {
        JS_FreeValue(g_cctx, srcv);
        return ret_error("check expects a source string");
    }

    JSValue g = JS_GetGlobalObject(g_cctx);
    JSValue fn = JS_GetPropertyStr(g_cctx, g, "__terrariumCheck");
    JS_FreeValue(g_cctx, g);
    JSValue dts = fetch_dts(g_cctx);
    JSValue args[2] = { srcv, dts };
    JSValue res = JS_Call(g_cctx, fn, JS_UNDEFINED, 2, args);
    JS_FreeValue(g_cctx, fn);
    JS_FreeValue(g_cctx, srcv);
    JS_FreeValue(g_cctx, dts);

    int64_t out;
    if (JS_IsException(res)) {
        JSValue exc = JS_GetException(g_cctx);
        const char *s = JS_ToCString(g_cctx, exc);
        char msgbuf[512];
        snprintf(msgbuf, sizeof(msgbuf), "TypeScript compiler error: %s", s ? s : "unknown");
        if (s) JS_FreeCString(g_cctx, s);
        JS_FreeValue(g_cctx, exc);
        out = ret_error(msgbuf);
    } else {
        out = ret_value(g_cctx, res);
    }
    JS_FreeValue(g_cctx, res);
    return out;
}

/* ------------------------------------------------------------------ */
/* eval entrypoint                                                     */
/* ------------------------------------------------------------------ */

__attribute__((export_name("eval")))
int64_t eval(int32_t ptr, int32_t len) {
    /* The argument is a msgpack string: the TypeScript source. Decode it in a
     * fresh user runtime (also used to run the stripped JS afterwards). */
    JSRuntime *rt = JS_NewRuntime();
    if (!rt) return ret_error("failed to create JS runtime");
    JS_SetMaxStackSize(rt, 256 * 1024);
    JSContext *ctx = JS_NewContext(rt);

    Rd r = { (const uint8_t *)(uintptr_t)(uint32_t)ptr, 0, (size_t)(uint32_t)len };
    JSValue srcv = mp_to_js(ctx, &r);
    size_t slen; const char *src = JS_ToCStringLen(ctx, &slen, srcv);

    int64_t out;
    if (!src) {
        out = ret_error("eval expects a source string");
        goto done_user_only;
    }

    /* --- compile: check (unless @ts-nocheck) + strip, in the compiler ctx --- */
    if (ensure_compiler()) {
        out = ret_error("failed to start the TypeScript compiler");
        goto done_src;
    }
    {
        JSValue g = JS_GetGlobalObject(g_cctx);
        JSValue fn = JS_GetPropertyStr(g_cctx, g, "__terrariumCompile");
        JS_FreeValue(g_cctx, g);
        JSValue csrc = JS_NewStringLen(g_cctx, src, slen);
        JSValue dts = fetch_dts(g_cctx);
        JSValue args[2] = { csrc, dts };
        JSValue res = JS_Call(g_cctx, fn, JS_UNDEFINED, 2, args);
        JS_FreeValue(g_cctx, fn);
        JS_FreeValue(g_cctx, csrc);
        JS_FreeValue(g_cctx, dts);

        if (JS_IsException(res)) {
            JSValue exc = JS_GetException(g_cctx);
            const char *s = JS_ToCString(g_cctx, exc);
            char msgbuf[512];
            snprintf(msgbuf, sizeof(msgbuf), "TypeScript compiler error: %s", s ? s : "unknown");
            if (s) JS_FreeCString(g_cctx, s);
            JS_FreeValue(g_cctx, exc);
            out = ret_error(msgbuf);
            goto done_src;
        }

        JSValue jerr = JS_GetPropertyStr(g_cctx, res, "error");
        if (JS_IsObject(jerr)) {
            /* A check / syntax failure: forward {message, type, line}. */
            JSValue jm = JS_GetPropertyStr(g_cctx, jerr, "message");
            JSValue jt = JS_GetPropertyStr(g_cctx, jerr, "type");
            JSValue jl = JS_GetPropertyStr(g_cctx, jerr, "line");
            const char *m = JS_ToCString(g_cctx, jm);
            const char *t = JS_IsString(jt) ? JS_ToCString(g_cctx, jt) : NULL;
            int has_line = JS_IsNumber(jl);
            int64_t line = 0;
            if (has_line) JS_ToInt64(g_cctx, &line, jl);
            out = ret_error_full(m ? m : "type check failed", t, has_line, line);
            if (m) JS_FreeCString(g_cctx, m);
            if (t) JS_FreeCString(g_cctx, t);
            JS_FreeValue(g_cctx, jm);
            JS_FreeValue(g_cctx, jt);
            JS_FreeValue(g_cctx, jl);
            JS_FreeValue(g_cctx, jerr);
            JS_FreeValue(g_cctx, res);
            goto done_src;
        }
        JS_FreeValue(g_cctx, jerr);

        JSValue jjs = JS_GetPropertyStr(g_cctx, res, "js");
        size_t jslen; const char *js = JS_ToCStringLen(g_cctx, &jslen, jjs);
        JS_FreeValue(g_cctx, res);
        if (!js) {
            JS_FreeValue(g_cctx, jjs);
            out = ret_error("TypeScript compiler returned no output");
            goto done_src;
        }

        /* --- run the stripped JS in the fresh user context --- */
        JSValue global = JS_GetGlobalObject(ctx);
        JS_SetPropertyStr(ctx, global, "__host",
                          JS_NewCFunction(ctx, js_host, "__host", 1));
        JS_FreeValue(ctx, global);
        JSValue pre = JS_Eval(ctx, PRELUDE, strlen(PRELUDE), "<prelude>", JS_EVAL_TYPE_GLOBAL);
        JS_FreeValue(ctx, pre);

        JSValue ures = JS_Eval(ctx, js, jslen, "<eval>", JS_EVAL_TYPE_GLOBAL);
        JS_FreeCString(g_cctx, js);
        JS_FreeValue(g_cctx, jjs);

        if (JS_IsException(ures)) {
            JSValue exc = JS_GetException(ctx);
            out = ret_error_exc(ctx, exc);
            JS_FreeValue(ctx, exc);
        } else {
            out = ret_value(ctx, ures);
        }
        JS_FreeValue(ctx, ures);
    }

done_src:
    JS_FreeCString(ctx, src);
done_user_only:
    JS_FreeValue(ctx, srcv);
    JS_FreeContext(ctx);
    JS_FreeRuntime(rt);
    return out;
}
